name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies  
      run: npm install

    - name: Run tests
      run: npm run test
    
    - name: Publish Coverage Report
      uses: Nef10/lcov-reporter-action@v0.3.0
      with:
        lcov-file: ./coverage/lcov.info
        pr-number: ${{ env.pr_number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
