name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies  
      run: npm install

    - name: Run tests
      run: npm run test
    
    - name: Publish Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.0
      with:
        lcov-file: ./coverage/lcov.info
       # pr-number: ${{ env.pr_number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.0.2
      # uses: joshjohanning/CodeCoverageSummary@v1.0.2
      with:
        filename: ./coverage/lcov.info
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
